### 1)

#### Подключение к базе данных

In [ ]:
!pip install psycopg2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import psycopg2

connection = psycopg2.connect(dbname='balance909', user='balance909', password='Sa_909_wuf;', host='89.108.115.118', port=5432)
cursor = connection.cursor()

In [ ]:
connection

<connection object at 0x7f8ef389fc20; dsn: 'user=balance909 password=xxx dbname=balance909 host=89.108.115.118 port=5432', closed: 0>

In [ ]:
cursor.execute("""
SELECT company_id, sum(count_product * price) 
FROM consumer_requirement_base cr 
	JOIN product p ON p.id=product_id 
	GROUP BY company_id
	ORDER BY company_id;
""")
y_i = cursor.fetchall()
y_i

[(1, 108350.0),
 (2, 1000000.0),
 (3, 25000000.0),
 (4, 999990.0),
 (5, 9999000.0),
 (6, 50.0),
 (7, 30000000.0),
 (8, 166315.0),
 (9, 34327300.0),
 (10, 774150.0),
 (11, 7499500.0),
 (12, 1200.0),
 (13, 600.0)]

### 2)

In [ ]:
cursor.execute("""SELECT cr.company_id, sum(count_product * price) 
FROM company_requirement cr 
	JOIN product p ON p.id=product_id 
	WHERE p.company_id = 1
	GROUP BY cr.company_id
	ORDER BY cr.company_id
""")
x_1j = cursor.fetchall()
x_1j

[(2, 4000.0), (9, 1036000.0), (10, 25000.0)]

#### Предобработка make_balance_table

In [ ]:
cursor.execute("""SELECT * FROM make_balance_table(ARRAY[1,2,3,4,5,6,7,8,9,10,11,12,13])""")
matrix = list(map(lambda x: x[0].split(';'), cursor.fetchall()))
print(matrix)

[['-', '1', '10', '11', '12', '13', '2', '3', '4', '5', '6', '7', '8', '9', 'Y'], ['1', '0', '4000', '0', '0', '0', '0', '0', '0', '1036000', '25000', '0', '0', '0', '108350'], ['2', '100000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1000000'], ['3', '0', '0', '1000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '25000000'], ['4', '199998', '0', '999990', '4999950', '0', '0', '0', '0', '0', '0', '0', '0', '99999', '999990'], ['5', '150000', '0', '0', '0', '1500000', '0', '0', '0', '0', '0', '0', '0', '0', '9999000'], ['6', '100', '0', '0', '0', '0', '8050', '0', '0', '0', '0', '0', '0', '0', '50'], ['7', '0', '0', '0', '0', '0', '0', '30000000', '0', '0', '0', '0', '0', '0', '30000000'], ['8', '0', '0', '0', '0', '0', '0', '0', '269700', '0', '0', '0', '0', '0', '166315'], ['9', '0', '350000', '35000', '0', '0', '0', '0', '0', '35000000', '7000', '0', '0', '0', '34327300'], ['10', '0', '195000', '0', '0', '0', '0', '0', '0', '0', '780000', '0', '0', '0', '77

In [ ]:
matrix[0][0] = '0'
matrix[0][-1] = '1000'
print(matrix)

[['0', '1', '10', '11', '12', '13', '2', '3', '4', '5', '6', '7', '8', '9', '1000'], ['1', '0', '4000', '0', '0', '0', '0', '0', '0', '1036000', '25000', '0', '0', '0', '108350'], ['2', '100000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1000000'], ['3', '0', '0', '1000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '25000000'], ['4', '199998', '0', '999990', '4999950', '0', '0', '0', '0', '0', '0', '0', '0', '99999', '999990'], ['5', '150000', '0', '0', '0', '1500000', '0', '0', '0', '0', '0', '0', '0', '0', '9999000'], ['6', '100', '0', '0', '0', '0', '8050', '0', '0', '0', '0', '0', '0', '0', '50'], ['7', '0', '0', '0', '0', '0', '0', '30000000', '0', '0', '0', '0', '0', '0', '30000000'], ['8', '0', '0', '0', '0', '0', '0', '0', '269700', '0', '0', '0', '0', '0', '166315'], ['9', '0', '350000', '35000', '0', '0', '0', '0', '0', '35000000', '7000', '0', '0', '0', '34327300'], ['10', '0', '195000', '0', '0', '0', '0', '0', '0', '0', '780000', '0', '0', '0', 

In [ ]:
matrix = list(map(lambda x: list(map(lambda y: int(y), x)), matrix))
print(matrix)

[[0, 1, 10, 11, 12, 13, 2, 3, 4, 5, 6, 7, 8, 9, 1000], [1, 0, 4000, 0, 0, 0, 0, 0, 0, 1036000, 25000, 0, 0, 0, 108350], [2, 100000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000000], [3, 0, 0, 1000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25000000], [4, 199998, 0, 999990, 4999950, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 999990], [5, 150000, 0, 0, 0, 1500000, 0, 0, 0, 0, 0, 0, 0, 0, 9999000], [6, 100, 0, 0, 0, 0, 8050, 0, 0, 0, 0, 0, 0, 0, 50], [7, 0, 0, 0, 0, 0, 0, 30000000, 0, 0, 0, 0, 0, 0, 30000000], [8, 0, 0, 0, 0, 0, 0, 0, 269700, 0, 0, 0, 0, 0, 166315], [9, 0, 350000, 35000, 0, 0, 0, 0, 0, 35000000, 7000, 0, 0, 0, 34327300], [10, 0, 195000, 0, 0, 0, 0, 0, 0, 0, 780000, 0, 0, 0, 774150], [11, 2500, 7500, 0, 0, 0, 0, 0, 0, 10000, 10000, 7500000, 0, 0, 7499500], [12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1200, 0, 1200], [13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600]]


In [ ]:
import numpy as np

np.set_printoptions(linewidth=100000, suppress=True)

In [ ]:
n = np.array(matrix)
print(n)

[[       0        1       10       11       12       13        2        3        4        5        6        7        8        9     1000]
 [       1        0     4000        0        0        0        0        0        0  1036000    25000        0        0        0   108350]
 [       2   100000        0        0        0        0        0        0        0        0        0        0        0        0  1000000]
 [       3        0        0  1000000        0        0        0        0        0        0        0        0        0        0 25000000]
 [       4   199998        0   999990  4999950        0        0        0        0        0        0        0        0    99999   999990]
 [       5   150000        0        0        0  1500000        0        0        0        0        0        0        0        0  9999000]
 [       6      100        0        0        0        0     8050        0        0        0        0        0        0        0       50]
 [       7        0        0      

In [ ]:
n = n[:, n[0].argsort()]
n

array([[       0,        1,        2,        3,        4,        5,        6,        7,        8,        9,       10,       11,       12,       13,     1000],
       [       1,        0,        0,        0,        0,  1036000,    25000,        0,        0,        0,     4000,        0,        0,        0,   108350],
       [       2,   100000,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,  1000000],
       [       3,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,  1000000,        0,        0, 25000000],
       [       4,   199998,        0,        0,        0,        0,        0,        0,        0,    99999,        0,   999990,  4999950,        0,   999990],
       [       5,   150000,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,  1500000,  9999000],
       [       6,      100,     8050,        0

### 3)

In [ ]:
x_y = n[1:, 1:]
x_y

array([[       0,        0,        0,        0,  1036000,    25000,        0,        0,        0,     4000,        0,        0,        0,   108350],
       [  100000,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,  1000000],
       [       0,        0,        0,        0,        0,        0,        0,        0,        0,        0,  1000000,        0,        0, 25000000],
       [  199998,        0,        0,        0,        0,        0,        0,        0,    99999,        0,   999990,  4999950,        0,   999990],
       [  150000,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,  1500000,  9999000],
       [     100,     8050,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,        0,       50],
       [       0,        0, 30000000,        0,        0,        0,        0,        0,        0,        0

In [ ]:
x_ij = x_y[:, :-1]
print(x_ij)

[[       0        0        0        0  1036000    25000        0        0        0     4000        0        0        0]
 [  100000        0        0        0        0        0        0        0        0        0        0        0        0]
 [       0        0        0        0        0        0        0        0        0        0  1000000        0        0]
 [  199998        0        0        0        0        0        0        0    99999        0   999990  4999950        0]
 [  150000        0        0        0        0        0        0        0        0        0        0        0  1500000]
 [     100     8050        0        0        0        0        0        0        0        0        0        0        0]
 [       0        0 30000000        0        0        0        0        0        0        0        0        0        0]
 [       0        0        0   269700        0        0        0        0        0        0        0        0        0]
 [       0        0        0        0 35

In [ ]:
y = x_y[:, -1]
print(y)

[  108350  1000000 25000000   999990  9999000       50 30000000   166315 34327300   774150  7499500     1200      600]


In [ ]:
x_i = x_y.sum(axis=1)
x_i

array([ 1173350,  1100000, 26000000,  7299927, 11649000,     8200, 60000000,   436015, 69719300,  1749150, 15029500,     2400,      600])

### 4)

In [ ]:
x_temp = np.array([x_i] * x_ij.shape[0])
print(x_temp)

[[ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11649000     8200 60000000   436015 69719300  1749150 15029500     2400      600]
 [ 1173350  1100000 26000000  7299927 11

In [ ]:
a = x_ij / x_temp
a

array([[   0.        ,    0.        ,    0.        ,    0.        ,    0.08893467,    3.04878049,    0.        ,    0.        ,    0.        ,    0.00228683,    0.        ,    0.        ,    0.        ],
       [   0.08522606,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.06653581,    0.        ,    0.        ],
       [   0.17045042,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.00143431,    0.        ,    0.06653515, 2083.3125    ,    0.        ],
       [   0.12783909,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.        ,    0.      

In [ ]:
print(y)

[  108350  1000000 25000000   999990  9999000       50 30000000   166315 34327300   774150  7499500     1200      600]


In [ ]:
import random

f = lambda x: x + random.randint(-40, 500)

new_y = f(y)
print(new_y)

[  108566  1000216 25000216  1000206  9999216      266 30000216   166531 34327516   774366  7499716     1416      816]


### 5), 6)

In [ ]:
e = np.eye(a.shape[0])
print(e)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
result = np.linalg.inv(e - a).dot(new_y)
print(result)

[ 1223007.63354356  1104448.1245616  26000301.62187641  7886559.63892075 12195564.1868424      8452.78430885 60000564.02524201   457904.48012068 71367377.8150477   1776455.41909176 15030786.85399145     2676.24420294      816.        ]


In [ ]:
cursor.close()